name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'ap-southeast-1'
      ECR_REPO: 'faliq/myrepo'
      IMAGE_TAG: '${{ github.sha }}'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
      if: ${{ matrix.language == 'java' }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      if: ${{ matrix.language == 'python' }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      if: ${{ matrix.language == 'node' }}

    - name: Build and Test
      run: |
        if [ -f "pom.xml" ]; then
          mvn clean package;
        elif [ -f "package.json" ]; then
          npm install;
        elif [ -f "requirements.txt" ]; then
          pip install -r requirements.txt && pytest;
        fi

    - name: Build Docker Image
      run: docker build -t $ECR_REPO:$IMAGE_TAG .

    - name: Push to ECR
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY}} 
        aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_KEY}}
        aws ecr get-login-password  --region ap-southeast-01 | docker login --username ${{ secrets.DOCKER_LOGIN }} --password-stdin ${{ secrets.DOCKER_TOKEN }} 061039780090.dkr.ecr.ap-southeast-1.amazonaws.com
        docker tag $ECR_REPO:$IMAGE_TAG 061039780090.dkr.ecr.ap-southeast-1.amazonaws.com$ECR_REPO:$IMAGE_TAG
        docker push 061039780090.dkr.ecr.ap-southeast-1.amazonaws.com$ECR_REPO:$IMAGE_TAG

    - name: Deploy to ECS
      run: |
        terraform init
        terraform plan