name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        language: [python, java, node]
        version: [3.8, 11, 14]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ${{ matrix.language }}
      if: matrix.language == 'python'
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}

    - name: Set up ${{ matrix.language }}
      if: matrix.language == 'java'
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.version }}

    - name: Set up ${{ matrix.language }}
      if: matrix.language == 'node'
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.version }}

    - name: Install dependencies
      run: |
        if [ "${{ matrix.language }}" == "python" ]; then
          pip install -r requirements.txt
        elif [ "${{ matrix.language }}" == "java" ]; then
          ./mvnw install
        elif [ "${{ matrix.language }}" == "node" ]; then
          npm install
        fi

    - name: Run tests
      run: |
        if [ "${{ matrix.language }}" == "python" ]; then
          pytest
        elif [ "${{ matrix.language }}" == "java" ]; then
          ./mvnw test
        elif [ "${{ matrix.language }}" == "node" ]; then
          npm test
        fi